spring.application.name=ProyectLP2
server.port=8082

# CONFIGURACIÓN PARA MYSQL NATIVO EN WINDOWS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Cambiado al puerto estándar 3306
#spring.datasource.url=jdbc:mysql://localhost:3306/cine?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

# Dialecto moderno recomendado para Spring Boot 3.x
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.sql=debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
security.jwt.secret-key=Y2luZW1hcHJveWVjdGxwMnVwZXVzZWN1cml0eWtleWJhc2U2NGVuY29kaW5nMjAyNQ==
security.jwt.expiration-time=300000

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop