version: '3.8'

services:
  # Servicio del Backend
  backend:
    build:
      # CORREGIDO: Usar el nombre de carpeta correcto 'ProyectLP2'
      context: ./ProyectLP2
      dockerfile: Dockerfile
    container_name: app-cine-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cine?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - cine-network

  # Servicio del Frontend
  frontend:
    build:
      # CORREGIDO: Usar el nombre de carpeta correcto 'Lp2-Frontend'
      context: ./Lp2-Frontend
      dockerfile: Dockerfile
    container_name: app-cine-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - cine-network

  # Servicio de la Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql-cine
    restart: always
    environment:
      MYSQL_DATABASE: cine
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cine-network

volumes:
  mysql_data:

networks:
  cine-network:
    driver: bridge
