# Usamos la imagen oficial de Maven como base
FROM maven:3.9.6-eclipse-temurin-21

# Establecemos el directorio de trabajo en /app
WORKDIR /app

# Copiamos todo el código fuente del proyecto (el contexto de build) a /app
COPY . .
